[database]
# Set where data should be stored.
# Examples:
#    sqlite:///database.db
#    mysql+pymysql://user:password@localhost/database
#    postgresql+psycopg2://user:password@localhost/database
#    mariadb+pymysql://user:password@localhost/database
# Form: dialect+driver://username:password@host:port/database
# Please make sure to install the appropriate database driver for your chosen database.
database_uri = sqlite:///database.db



